watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop"
  reload_command: "komorebic stop && komorebic start --whkd"
bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 28
    padding:
      top: 3
      left: 4
      bottom: 0
      right: 4
    widgets:
      left: ["home", "active_window", "komorebi_workspaces"]
      center: ["media"]
      right: [ "cava", "systray", "volume", "weather", "clock"]
widgets:
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      framerate: 120
      sleep_timer: 60
      hide_empty: true
      gradient: 0
      foreground: "#e2cca9"
      container_padding:
        top: 3
        right: 2
        bottom: 3
        left: 3
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\uf001</span> {artist} - {title}"
      hide_empty: true
      max_field_size:
        label: 150
      show_thumbnail: false
      controls_hide: true
      thumbnail_alpha: 50
      thumbnail_padding: 70
      thumbnail_corner_radius: 5
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      callbacks:
        on_left: "do_nothing"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf017</span> {%d/%m/%Y, %H:%M:%S}"
      timezones: [] #Looking up time zone info from registry
      calendar:
        alignment: "center"
      callbacks:
        on_left: "toggle_calendar"
        on_right: "do_nothing"
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      animation: true
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "\u26a1 Offline"
      label_workspace_btn: "\udb81\udc3d"
      label_workspace_active_btn: "\udb81\udc3e"
      label_workspace_populated_btn: "\udb81\udc3e"
      label_default_name: "{index}"
      label_zero_index: true
      hide_empty_workspaces: false
      hide_if_offline: true
      animation: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      api_key: "****"
      update_interval: 600
      units: "metric"
      hide_decimal: true
      location: "The Netherlands, Amsterdam-Zuidoost"
      show_alerts: true
      weather_card:
        alignment: "center"
        offset_left: 150
      callbacks:
        on_left: "toggle_card"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyIcyDay: "\udb81\udd98"
        snowyIcyNight: "\udb81\udd98"
        blizzardDay: "\uebaa"
        default: "\uebaa"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
        on_middle: "toggle_mute"
  pomodoro:
    type: "yasb.pomodoro.PomodoroWidget"
    options:
      label: "<span>{icon}</span> {remaining}"
      label_alt: "<span>{icon}</span> {session}/{total_sessions} - {status}"
      work_duration: 25
      break_duration: 5
      long_break_duration: 15
      long_break_interval: 4
      auto_start_breaks: true
      auto_start_work: true
      sound_notification: true
      show_notification: true
      hide_on_break: false
      session_target: 8
      icons:
        work: "\uf252"
        break: "\uf253"
        paused: "\uf254"
      container_padding:
        top: 0
        left: 12
        bottom: 0
        right: 12
      menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        circle_background_color: "#09ffffff"
        circle_work_progress_color: "#88c0d0"
        circle_break_progress_color: "#a3be8c"
        circle_thickness: 8
        circle_size: 160
      callbacks:
        on_left: "toggle_menu"
        on_middle: "reset_timer"
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\ue8e5</span>"
      menu_list:
      - { title: "~/Downloads", path: "D:\\Downloads" }
      - { title: "~/Documents", path: "D:\\Documents" }
      - { title: "~/Pictures", path: "D:\\Pictures" }
      - { title: "C:\\>", path: "C:\\" }
      - { title: "D:\\>", path: "C:\\" }
      - { title: "E:\\>", path: "C:\\" }

      system_menu: true
      power_menu: true
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "System"
      offset_top: 6
      offset_left: 0
      container_padding: 
        top: 0
        left: 0
        bottom: 0
        right: 0
      alignment: "left"
      direction: "down"
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: False
      blur: False
      blur_background: True
      animation_duration: 100 # Milisecond
      button_row: 4 # Number of buttons in row, min 1 max 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[process][name]}"
      label_alt: ""
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 40
      max_length_ellipsis: "..."
      monitor_exclusive: false
      callbacks:
        on_left: "do_nothing"
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\uf053"
      label_expanded: "\uf054"
      label_position: "left" # Can be "left" or "right"
      icon_size: 16 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: true
      container_padding:
          left: 0
          top: 0
          right: 0
          bottom: 0
      btn_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
